amcl:
  ros__parameters:
    use_sim_time: True
    map_topic: /map
    min_particles: 2000
    max_particles: 80000
    set_initial_pose: True
    initial_pose:
      x: 0.2
      y: 0.0
      z: 0.0
      yaw: 0.0
    # Parámetros de marcos de referencia (Frames)
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    global_frame_id: "map"

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "my_map.yaml"
    topic_name: "map"
    frame_id: "map"